test_project/chat_project_streaming/chatbot_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

test_project/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

test_project/mypoll/config/urls.py
#url Conf (Url Dispatcher, Url Mapping)
#url 경로와 view를 연결. 어떤 url로 요청이 들어오면 어떤 view가 실행될지를 연결 및 설정

"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include


# from polls.views import welcome


urlpatterns = [
    path('admin/', admin.site.urls),
    #polls/ 시작하는 url경로로 요청이 들어오면 polls앱/urls.py 의 설정에 가서 나머지를 확인
    path("polls/", include("polls.urls")),
    path("account/", include("account.urls"))
    # path('polls/welcome', welcome, name="poll_welcome"), #1. client 요청경로 , 2. 호출할 view, 3. name="설정이름"
   
]

from django.conf.urls.static import static
from . import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#MEDIA_URL 경로로 요청이 들어오면 어느 디렉토리를 찾아야 하는지 설정
## 개발 서버에서 설정 필요.
## 운영 환경(웹서버+MSGI)에서는 업로드 파일도 static 파일로 간주해서 웹 서버가 처리하도록 설정

test_project/mypoll/polls/urls.py
#polls app 에 대한 url-view 매핑 파일 (url Conf)

#URLConf - urlpatterns = [매핑설정]
#매핑설정 - path("url경로", View, name="설정식별이름") 함수를 사용

from django.urls import path
from . import views #상대 경로로 import '.'  현재 모듈이 있는 패키지

app_name = "polls" # 전체 설정에 대한 prefix(namespace). 
                   # 설정 name()에 공통적으로 붙일 이름 ("app_name:name")
urlpatterns =[
    path("welcome", views.welcome, name="welcome"),
    path("vote_list", views.list, name="list"),
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path("vote_create", views.vote_create, name="vote_create"),
    path("vote_delete/<int:question_id>", views.vote_delete, name="vote_delete")
]


# polls/vote_form/<path 파라미터 값 타입 :view 의 파라미터 변수명>
# <int: #path parameter 값을 int로 전달해라
# <   : qeustion_id> # view의 question_id 변수로 전달해라.
# type: int, str

test_project/mypoll/polls/models.py
# 모델 클래스들을 정의
from django.db import models

# 모델 클래스 정의 - Question(설문 질문) - Choice(설문의 보기)
##1.Models.Model 을 상속
##2. class 변수로 Field들을 정의 : Field == DB column, Model 객체의 Instance 변수. 이 둘에 대한 설정

# Create your models here.

#Modle class 정의 할 때 primary key Field를 선언하지 않으면.id (int outo_increment)으로 자동 생성
class Question(models.Model):
    #Field 정의 : 변수명 -(instance변수명, column 이름)
    #            Field 객체를 할당 Field 객체 - coulum 설정(type, null 허용여부,...)
    question_text = models.CharField(max_length=200) #CharField() -> 문자열타입(varchar)
    pub_date = models.DateTimeField(auto_now_add=True)
    #  DATETIMEField : 일시 타입(datetime, datetime.datetime)
    # auto_now_add: insert 될 때 일시를 자동 입력

    def __str__(self):
        return f"{self.id}. {self.question_text}"

#보기 테이블
class Choice(models.Model):

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) # 정수타입, (int, int)
    question = models.ForeignKey(
        Question, # 참조할 Model Class
        on_delete=models.CASCADE# 참조 값이 삭제된 경우 어떻게 하는지 -> chachde 삭제
    )  #FK -> Quesiont의 id를 참조.
    
    def __str__(self):
        return f"{self.id}. {self.choice_text}"

test_project/mypoll/polls/forms.py
# polls/froms.py

from django import forms

# Form 클래스를 정의 - Forms.Form 을 상속
## Form 클래스 : 입력 폼들을 모아서 정의한 클래스
##     -Form Field: 개별 입력 폼(input) 들을 정의
##                  클래스 변수로 정의. 입력 폼 양식 - 파이썬 타입 관련되어 FormField 객체를 할당

## 설문 질문 등록 폼
class QuestionForm(forms.Form):
    #Form Field - > 질문 입력
    #변수명 (요청 파라미터 name) = FormField(): 어떤 값을 입력 받을지 타입.
    #Form Field 1개 -> 한개 이름의요청파라미터 입력 태그를 설정
    ## 같은 이름으로 여러개 입력을 받을 경우 -> Form set 이용해서 구현
    question_text = forms.CharField( # 문자열 입력 폼 - View 에서 문자열로 읽기
        label="", #입력에 대한 label을 설정.
        max_length=200, # 최대 입력 글자 수.
        required=True, # 필수 입력인지 여부
        widget=forms.TextInput( #widget은 input 태그를 지정.
            attrs={"class": "form-control"} #입력 tag의 attribute 설정
        )
    )
     #검증 메소드를 추가. -> 업무규칙에 의한 검증
        #메소드 이름 규칙 : 1. 개별 Field들을 검증 - clean_필드명
        #                  2. 전체 입력 데이터들을 검증 - clean
        # 검증 메소드는 기본 검증을 하고 나서 호출한다.
        # - 구현 : 검증 통과 - return 요청파라미터 값. 검증오류 : raise ValidationError
        
    def clean_question_text(self):
        txt = self.cleaned_data['question_text'].strip() # 기본 검증을 통과한 입력값
        if len(txt) <= 5:
            raise forms.ValidationError("질문은 6글자 이상 입력하세요")

        return txt


class ChoiceForm(forms.Form):

    choice_text = forms.CharField(
        label="", #라벨을 생성하지 않게 한다.
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={"class":"form-control"})
    )
    def clean_question_text(self):
        txt = self.cleaned_data['question_text'].strip() # 기본 검증을 통과한 입력값
        if len(txt) <= 2:
            raise forms.ValidationError("보기는 2글자 이상 입력하세요")

        return txt

#ChoiceForm을 이용해서 FormSet 클래스를 성장
# FormSet : Form + Set : Form들의 집합
#           Form클래스의 내용을 붕복해서 가지는 class
#           특정 input 양식을 반복적으로 여러개 가지는 입력 페이지를 구성할 때
#           같은 이름으로 여러개의 입력을 받아야 할 때

ChoiceFormSet = forms.formset_factory(
    ChoiceForm, #Form클래스
    extra=2 #Form 을 몇 개 반복해서 만들지 갯수
)

test_project/mypoll/polls/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse #url conf 의 설정 이름으로 url을 조회하는 함수
from datetime import datetime
from django.http import HttpResponse
from .models import Question, Choice
from django.db import transaction #db transaction 처리
from django.core.paginator import Paginator

# Create your views here.

# 설문 welcome page
# 요청 -> 인삿말 화면 응답.

def welcome(request):
    print("welcome 실행")
    #요청처리
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    #응답화면 생성 -> template 호출(template이 사용할 값을 전달. : now 값)
    response = render( #template을 호출 - 결과 -> HttpResponse 로 반환
        request, #HttpRequest
        "polls/welcome.html", #호출할 템플릿의 경로
        {"now":now} #template에 전달할 값들. name-value 로 전달
                    #Context Value 라고 한다.
    )
    print(type(response)) # server를 실행한 터미널에 출력
    return response


def welcome_old(request):
    print("welcome 실행")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    #처리 결과 페이지 생성 -> html str 구현

    res_html = f"""<!doctype html>
<html>
    <head>
        <title>설문 main</title>
    </head> 
    <body>
        <h1>Welcom</h1>
        <p>저희 설문 페이지를 방문해주셔서 감사합니다.</p>
        현재시간: {now}
    </body>
</html>
"""
    res = HttpResponse(res_html)
    return res

# 설문(질문) 목록 조회
## 전체 question들을 조회해서 목록 html을 반환
## 요청 url : polls/list
## view 함수 : list
## template:polls/list.html
#################################
#페이징 처리 안 한 list
def list_old(request):
    # 1. DB에서 질문목록 조회 - > 모델 사용
    question_list = Question.objects.all().order_by("-pub_date")
    # 2. 응답페이지를 생성(template 사용) -> 반환
    return render(request,"polls/list.html", {"question_list":question_list})

####################
#페이징 처리 list
#
# - template 호출 전달할 Context Value
#   - 현재 페이지의 데이터 -page 객체
#   - 현재 페이지가 속한 그룹의 페이지 번호 start/end index
#   - 현재 페이지 그룹의 시작 페이지가 이전 페이지가 있는지 여부, 있다면 이전 페이지 번호
#   - 현재 페이지 그룹의 끝 페이지가 다음 페이지가 있는지 여부, 있다면 다음 페이지 번호

def list(request):
    paginate_by = 10 # 한 페이지당 데이터 개수
    page_group_count = 10 # 페이지 그룹당 페이지 수
    # http://ip:port/polls/list?page=6
    current_page = int(request.GET.get("page", 1)) #현재 조회요청이 들어온 페이지 번호. GET 방식의 요청파라미터

    #paginator
    q_list = Question.objects.all().order_by("-pk")
    pn = Paginator(q_list, paginate_by)

    #현재 페이지가 속한 Page
    start_index = int((current_page -1)/page_group_count)*page_group_count
    end_index = start_index + page_group_count

    page_range = pn.page_range[start_index : end_index] # 시작~끝페이지 번호조회

    #templet 에 전달할 context value dictionary
    context_value = {
        "page_range": page_range,
        "question_list": pn.page(current_page) #page[Question]
    }

    #pageGroup 의 시작페이지가 이전 페이지가 있는지 여부, 이전페이지 번호
    #PageGroup의 마지막 페이지가 다음페이지가 있는지 여부, 다음 페이지 번호

    start_page = pn.page(page_range[0]) # 시작 페이지 page 객체
    end_page = pn.page(page_range[-1]) # 마지막 페이지 page 객체

    if start_page.has_previous():
        context_value['has_previous'] = start_page.has_previous()
        context_value['previous_page_number']= start_page.previous_page_number()

    if end_page.has_next():
        context_value['has_next'] = end_page.has_next()
        context_value['next_page_number'] = end_page.next_page_number()

    # 응답 template 호출

    return render(
        request, "polls/list.html", context_value
    )



# 개별 설문을 할 수 있는 페이지(설문 폼)로 이동
## 질문 id를 path parameter로 받아서 그 질문과 보기를 조회해서 화면에 출력
## 설문 입력 폼 작성
## path parameter : http://ip:port/path1/path2/path3/전달값1/전달값2
## request(요청)parameter: http://ip:port/path1/path2/path?name=전달값1&전달값2

# 요청 url:  /polls/vote_form/질문ID
# view 함수: vote_form
#template :  정상 polls/vote_form.html
##           오류 polls/error.html

def vote_form(request, question_id):
    #question_id 파라미터 -  path parameter 값을 받을 변수
    #view 함수의 두번째 파라미터 부터는 path parameter를 받을 변수들.
    ## 파라미터 변수명은 url.py에 등록한 변수명으로 선언하면 된다.

    #1. DB에서 question_id로 질문을 조회
    try:
        question = Question.objects.get(pk=question_id)
        # 응답화면 요청
        return render(
                request,
                "polls/vote_form.html",
                {"question":question}
            )
    except Exception as e :
        print(f"발생한 에러: {e}") # 터미널(서버창)에 실제 에러 이유를 출력
        return render(
            request,
            "error.html",
            {"error_message": f"요청하신 {question_id}번 질문이 없습니다."}
        )



# 설문 처리 하기
## 선택한 보기(Choice)의 votes를 1 증가. 투표 결과를 보여주는 페이지로 이동

# 요청 URL :  polls/vote
# view 함수: vote
# 응답 :  정상- polls/vote_result.html
#         오류- polls/vote_form.html

#form 입력 -> 요청 파라미터로 읽는다.
#요청 파라미터: GET - request.GET -> dictionary {"요청 파라미터이름":"요청 파라미터 값"}
#              POST - request.POST -> dictionary

def vote(request):
     #요청 파라미터 조회
    choice_id = request.POST.get('choice') # 선택된 보기의 ID
    question_id = request.POST.get('question_id') # 질문 ID

    
    ##################
    # 쿠키(Cookie)를 이용해서 현재 사용자가 이미 투표한 적이 있는 질문이면 투표를 못 하게 한다.)
    #  - 쿠키 예제 연습(실제 DB를 이용해서 처리. 사용자-투표질문번호 테이블 이용.)
    #  -쿠키에 voted_question에 요청한 question_id가 있는지 여부 확인.
    #       -있으면 error_message와 함께 투표를 하지 못 했다고 vote_form으로 이동
    #       -없으면 투표처리. -> cookie voted_question에 투표 질문 ID를 추가.

    voted_question_ids = request.COOKIES.get('voted_question') #"1,7,10"
    if voted_question_ids:
        q_id_list = voted_question_ids.split(",") # ["1", "7", "10"]
        if question_id in q_id_list:
            question = Question.objects.get(pk=question)
            return render(request, "polls/vote_form.html",
                         {"question":question, "error_message":"이미 투표한 질문입니다."})
   
    # choice-id가 넘어왔다면 choice 의 votes 를 증가
    if choice_id != None:
        selected_choice = Choice.objects.get(pk=choice_id)
        selected_choice.votes += 1
        selected_choice.save() # update
    ############
    # voted_question Cookie에 투표한 질문_ID 추가
        voted_question_ids = str(question_id) if not voted_question_ids else f"{voted_question_ids},{question_id}"
    
        #TODO: 업데이트 결과를 보여주는 View(vote_result)를 redirect 방식으로 요청
        #urls.py 에 path 에 등록된 이름으로 url을 등록
        # app_name:설정이름
        # path parameter 가 있는 경우 args=[path para 값, ..]

        url = reverse("polls:vote_result", args=[question_id])
        print(type(url), url)
        response=redirect(url)
        response.set_cookie("voted_question", voted_question_ids)
        return response
    
        # 결과 페이지 - question을 조회
        # question = Question.objects.get(pk=question_id)
        # return render(
        #     request, "polls/vote_result.html", {"question":question}
        # )
    else: # choice를 선택하지 않고 요청한 경우
        question = Question.objects.get(pk=question_id)
        return render(
            request,
            "polls/vote_form.html",
            {"question":question, "error_message":"보기를 선택하세요"}
        )

# 개별 질문의 투표 결과를 보여주는 View
# 요청 URL: /polls/vote_result/<question_id>
# View 함수: vote_result
# 응답 : polls/vote_result.html
def vote_result(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(
        request, "polls/vote_result.html", {"question":question}
    )


# 설문(질문)을 등록처리.
# 요청 URL: /polls/vote_create
# view 함수 : vote_create
#           - HTTP 요청 방식에 따라 입력 양식을 제공할지/ 처리할지 결정
#           - GET: 입력 양식 적용(설문문제와 보기를 입력할 수 있는 화면)
#           - POST: 등록처리
# 응답 :  - get c처리 : (template) polls/vote_create.html
#         - post 처리: redirect 방식 응답 ==> list_view 를 요청
# HTTP 요청방식 조회 - request.method(str:"GET", "POST")

def vote_create_old(request):
    http_method = request.method
    if http_method == "GET":
            #입력 처리
        return render(request, "polls/vote_create.html")

    elif http_method == "POST":
            # 등록처리
            # 1. 요청(path) 파라미터 읽기
            # 2. 요청 파라미터 검증. - 성공 -> 처리 , 실패 -> 입력폼페이지(에러페이지) 를 응답
            # 3. 업무처리 -> db작업
            # 4. 응답.

            # 요청파라미터 조회 - request.POST(GET) => dictionary 구현체
            # 요청 파라미터 중 question_text를 조회
        question_text = request.POST.get("question_text")
            # 요청파라미터 중 choice_text 를 조회(같은 이름으로 여러개 전달)
            # choice_text=보기1&choice_text=보기2&...
        choice_list = request.POST.getlist("choice_text") #list[str]

            # 요청파라미터 검증 (질문 : 1글자 이상, 보기: 2개 이상 각각 1글자 이상)
        if not question_text: #빈문자열일 경우
                return render(
                    request, "polls/vote_create.html",
                    {"error_msg": "문제를 한 글자 이상 입력하세요.",
                    "question_text":question_text,
                    "choice_list":choice_list}

                )    
            ## 보기 검증, choice_text가 넘어온 게 없거나
            ##          (choice_text가 넘어온 게 있는데 빈 문자열로 구성)
        if not choice_list or (choice_list and len([c for c in choice_list if c.strip()]) < 2):
                return render(
                    request, "polls/vote_create.html",
                    {"error_msg": "보기는 두개 이상 입력해야 합니다.",
                    "question_text":question_text,
                    "choice_list":choice_list}
                    )

        try:
            #with block을 정상적으로 처리하면 commit 발생
            #with block 실행중 Exception 이 발생하면 rollback(insert 처음 상태로 돌린다.)
            with transaction.atomic():

                #검증통과 -> DB에 저장(Instert)
                # 모델.save()
                q = Question(question_text=question_text) #id/pub_date 자동입력
                q.save()

                # raise Exception("문제가 발생했습니다.")

                for c in choice_list:
                    choice = Choice(choice_text=c, question=q) #id/vote 자동입력
                    choice.save()

        except Exception as e :
            # error page 이동
            return render(request, "error.html", {"error_message":"질문을 저장하는 도중 문제가 발생했습니다. 관리자에게 문의하세요"})

            # 4. 응답 - list로 redirect 방식으로 이동
        return redirect(reverse("polls:list"))
    
from .forms import QuestionForm, ChoiceFormSet

# forms.py 의 Form을 이용한 요청 파라미터 처리 view gkatn

@login_required
def vote_create(request):
    
    if request.method == "GET":

test_project/mypoll/polls/templates/polls/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<h1>
    <a href="{% url 'polls:welcome' %}">설문 홈</a>
    
    <p>
        요청하신 것을 처리하지 못 했습니다<br>
        에러메세지:{{error_message}}
    </p>
</body>
</html>

test_project/mypoll/polls/templates/polls/list.html
<!--''layout/main_layout.html' 레이아웃을 여기로 불러와라'-->
{% extends 'layout/main_layout.html' %}

<!--main_layout.htmldml block에 넣을 내용들만 정의-->
{%block title%} 설문 목록 {%endblock title%}

{%block contents%}
<h1>설문목록</h1>
        <ul class="list-group">
            <!--반복문 - question_list(context_value:QuertySet)의 Question들을 출력-->
        {% for question in question_list %}
            <li class="list-group-item list-group-item-action">
                <a href="{% url 'polls:vote_form' question.pk %}">
                    {{question.pk}}. {{question.question_text}}
                </a>
                {% if user.is_authenticated %}
                <a href="{% url 'polls:vote_delete' question.pk %}" class="btn btn-danger btn-sm">
                    질문삭제
                </a>   
                {% endif %}
            </li>
        {% empty %}
        {# 처음 부터 question_list가 비어있으면#}
        <b>아직 등록된 질문이 없습니다.</b>
        {% endfor %}
        </ul>
<!-- 페이징 처리 - 페이지 링크들 출력-->
<div id="page_group" class="pagination mt-3">
    {# 이전 페이지 그룹으로 이동하는 버튼 #}
    {% if has_previous %}
        <li class="page-item">
            <a href="{% url 'polls:list' %}?page={{previous_page_number}}" class="page-link"> 
                ◀이전
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
        <span class="page-link">◀</span>
        </li>
    {% endif %}

    {# 현재 페이지 그룹의 페이지들로 이동하는 링크 - 현재 페이지는 링크를 걸지 않는다.#}
    {% for page_no in page_range %}
    <!-- question_list:Page 객체  page객체.number -> 페이지 번호-->
        {%if question_list.number == page_no %}
            <li class="page-item active">
                <span class="page-link">{{page_no}}</span>
            </li>
        {% else %}
        <li class="page-item">
            <a href="{% url 'polls:list' %}?page={{page_no}}" class="page-link">{{page_no}}</a>
        </li>
        {% endif %}    
    {% endfor %}
    
    {# 다음 페이지 그룹으로 이동하는 버튼 #}
        {% if has_next %}
        <li class="page-item">
            <a href="{% url 'polls:list' %}?page={{next_page_number}}" class="page-link"> 
                다음▶
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
        <span class="page-link">▶</span>
        </li>
    {% endif %}
</div>
{%endblock contents%}

test_project/mypoll/polls/templates/polls/vote_create.html
{%extends "layout/main_layout.html" %}

{%block title%}설문 등록{%endblock title%}

{%block contents%}
<h1>설문 문제 등록</h1>
    {% if error_msg %}
        <dif style="color: red">{{error_msg}}</dif>
    {%endif%}
    <form method="post"> 
        {% csrf_token %}
        <h3>질문</h3>
        <input type="text" name="question_text" class="form_control" value="{{question_text}}" required>
        <h3>보기</h3>
        <div id="choice_layer">
            {%if not choice_list%}

            <div><input type="text" name="choice_text" class="form_control" required></div>
            <div><input type="text" name="choice_text" class="form_control" required></div>
            {% else %}
                {% for choice in choice_list%}
                <div>
                    <input type="text" name="choice_text" class="form_control" value="{{choice}}" required>
                </div>
                {%endfor%}
            {% endif %}
        </div>
        <div id="btn_layer">
            <button type="button" onclick="addChoice()"class="btn btn-info">보기추가</button>
            <button type="button" onclick="delChoice()"class="btn btn-info">보기삭제</button>
            <button type="submit" class="btn btn-primary">문제 등록</button>
        </div>
    </form>
{%endblock contents%}
{%block javascript%}
    <script>
        function addChoice(){
            // <input type="text" name="choice_text" size="100"><br>
            const input = document.createElement("input");
            input.setAttribute("type", "text");
            input.setAttribute("name", "choice_text");
            input.setAttribute('size', "from-control");
            input.setAttribute("required", ture);
            // const br = document.createElement("br");

            //input + br 을 묶을 div 생성
            const div = document.createElement("div");
            div.appendChild(input);
            // div.appendChild(br);

            //추가할 초이스 레이어 를 조회
            const layer = document.querySelector("#choice_layer");
            layer.appendChild(div);
        }
        function delChoice(){
            // #choice_layer에서 보기 입력폼을 하나 삭제
            // 보기 입력이 두개이면 삭제하지 않는다 (최소 2개는 유지)
            // 삭제: 부모노드.removeChild("삭제할 노드")
            const layer = document.querySelector("#choice_layer");
            if (layer.children.length > 2){
                //삭제
              layer.removeChild(layer.lastChild);
            }else{
                //유지
                alert("보기가 두개이면 삭제가 안됩니다.");
            }
        }
    </script>
{%endblock javascript%}

test_project/mypoll/polls/templates/polls/vote_form.html
{%extends "layout/main_layout.html"%}


{%block title%}설문하기{%endblock title%}

{%block contents%}
<h1>설문 하기</h1>
<h2>{{question.question_text}}</h2>

{% if error_message %}
<div style="color:red;font-size:0.9em">
    {{error_message}}
</div>
{%endif%}

<form action="{% url 'polls:vote' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="question_id" value="{{question.pk}}">
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" class="form-check-input" value="{{choice.pk}}" id="{{choice.pk}}">
         <label for="{{choice.pk}}">{{choice.choice_text}}</label><br>
    {%endfor%}
    <button type="submit" class="btn btn-primary">투표</button>
    <button type="reset" class="btn btn-primary" >선택해제</button>
</form>
{%endblock contents%}

test_project/mypoll/polls/templates/polls/vote_result.html
{%extends "layout/main_layout.html"%}    
{%block title%}설문결과{%endblock title%}

{%block constnets%}
    <h1>설문 결과</h1>
    <h2>{{question.pk}}. {{question.question_text}}</h2>
    <ol>
        {% for choice in question.choice_set.all %}
            <li>{{choice.choice_text}} - {{choice.votes}}</li>
        {% endfor %}
    </ol>
{%endblock constnets%}

test_project/mypoll/polls/templates/polls/welcome.html
<!--polls/templates/polls/welcome.html-->
<!--HTML이 아니라 django templete 따라서 html의 언어만 사용하지 않음-->

{% block title %} Home {% endblock title %}
{% block contents %}

        <h1>Welcom-templete</h1>
        <img src="/static/polls/imgs/survay.png">

        <p>저희 설문 페이지를 방문해주셔서 감사합니다.</p>
        현재시간: {{now}} <!--context value now를 출력-->
        <p>
            <a href="{%url 'polls:list'%}">질문 목록</a>
            <a href="{%url 'polls:vote_create'%}">질문 등록</a>
        </p>

{% endblock contents %}